
version: '3'
services:

  pyspark:
    image:    dxlab-spark
    command:  pyspark
    extra_hosts:
      - "netcat:11.0.0.10"   
      - "tweets:11.0.0.11"  
    
    
  netcat:
    image:    dxlab-spark
    networks:
      default: 
        ipv4_address: 11.0.0.10


  tweets:
    build:    .
    image:    dxlab-spark
    command:  python python/tweets-tcp.py 11.0.0.11 9999
    working_dir: /root
    volumes:
      - .:/root
    networks:
      default: 
        ipv4_address: 11.0.0.11

      
networks:
  default:
    ipam:
     config:
       - subnet: 11.0.0.0/16
