
version: '3'
services:

  master:
    image:    jaeo/dxlab-spark
    command:  spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080 
        

  worker:
    image:    jaeo/dxlab-spark
    command:  spark-class org.apache.spark.deploy.worker.Worker spark://172.18.0.2:7077
    hostname: worker
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8081:8081
    volumes:
      - ./data/example.txt:/root/example.txt 


  

  